useful git commands
lab-antwerp-1/home pull request #111
Opened 2021-10-27 18:41 UTC by ashenafykebede

## Checklists

### General Checks

- [ ] the branch is up to date with `main`/`master`
- [ ] the code works when pulled and run locally
- [ ] All CI checks pass
- [ ] all conflicts are resolved (if any)
- [ ] PR has a descriptive title
- [ ] PR has appropriate labels and milestones for easy identification
- [ ] PR it is assigned to the owner
- [ ] reviewers are assigned
- [ ] the PR contributes only one focused change
- [ ] It is in the appropriate column in the project board (if necessary)
- [ ] has short and clear description
- [ ] is linked to an issue (if it is related)
- [ ] feedback is addressed (if any and if it is appropriate feedback.)

### Markdown

- [ ] the markdown source is formatted
- [ ] spelling and grammar is correct in all text
- [ ] The markdown looks correct when you preview the file
- [ ] all links and images work
- [ ] any embedded code snippets are formatted

2021-11-02 12:16 UTC, gelilaa requested changes
hey @ashenafykebede  to pass the PR checks, can you please make a small change on your branch and push again?

2021-11-03 08:14 UTC, ashenafykebede commented
Dear @gelilaa 

I don't think the PR check fails because of my code. The error is in the main repo?

Can you check it?

Thank you

2021-11-04 06:54 UTC, gelilaa commented
@ashenafykebede, you are right the problem was ‘kebabcase’ naming conventions. And it has been fixed with another PR merge. 

 That is why I asked you to make a small( simple) change so that your workflow can pick up on the changes. It can be a small change (a space, a word….)

2021-11-07 16:00 UTC, gelilaa approved these changes

2021-11-07 16:00 UTC, merged