add js snippet
lab-antwerp-1/home pull request #172
Opened 2021-12-02 03:45 UTC by aviv82

# add js snippet for event listener change class tag on scroll

## Checklists

### General Checks

- [ ] the branch is up to date with `main`/`master`
- [ ] the code works when pulled and run locally
- [ ] All CI checks pass
- [ ] all conflicts are resolved (if any)
- [ ] PR has a descriptive title
- [ ] PR has appropriate labels and milestones for easy identification
- [ ] PR it is assigned to the owner
- [ ] reviewers are assigned
- [ ] the PR contributes only one focused change
- [ ] It is in the appropriate column in the project board (if necessary)
- [ ] has short and clear description
- [ ] is linked to an issue (if it is related)
- [ ] feedback is addressed (if any and if it is appropriate feedback.)

### Markdown

- [ ] the markdown source is formatted
- [ ] spelling and grammar is correct in all text
- [ ] The markdown looks correct when you preview the file
- [ ] all links and images work
- [ ] any embedded code snippets are formatted

2021-12-06 08:00 UTC, arnochauveau requested changes
Very good job on describing this snippet, @aviv82 !
The comments were very clear ✨

I've added some comments to the PR for some things that weren't 100% correct.

2021-12-06 08:00 UTC, arnochauveau commented on snippets/javascript/class-tag-on-scroll.md
> +    // ^ here we assign a variable - i - and set a condition for its value
You forgot something important here: **It will also loop until the condition is true**

2021-12-06 08:00 UTC, arnochauveau commented on snippets/javascript/class-tag-on-scroll.md
> +of the second tag */
Almost! 🙂 addEventListener is a **function** with two parameters:
1. the **name of the event** as a string
2. the name of a **function that needs to be executed** when the event is triggered

2021-12-06 08:00 UTC, arnochauveau commented on snippets/javascript/class-tag-on-scroll.md
> +  class="container hide"*/
Note that `hide` in this example is a **class name** of an element and **not the element itself**.

querySelector can use these **class names** to get the element itself.

2021-12-06 08:00 UTC, arnochauveau commented on snippets/javascript/class-tag-on-scroll.md
> +      or transformations for the new - show - tag in the css */
Note that the hide class isn't actually being changed. The thing that happens is that the `show` class will be added to the classes which will result in something like this: 

```html
<div class="hide show"></div>
```

2021-12-06 09:10 UTC, aviv82 commented
thank you Arno! i will edit my comments asap

2021-12-07 02:53 UTC, aviv82 commented
edited! thank you so much for the feedback. i learned a lot just from trying to figure this snippet out, and you helped me fill the gaps in my understanding. 🙂

2021-12-07 09:28 UTC, merged