Vocabulary js var
lab-antwerp-1/home pull request #186
Opened 2021-12-04 01:56 UTC by aviv82

# add a short description of different variable keywords in js 

## Checklists

### General Checks

- [ ] the branch is up to date with `main`/`master`
- [ ] the code works when pulled and run locally
- [ ] All CI checks pass
- [ ] all conflicts are resolved (if any)
- [ ] PR has a descriptive title
- [ ] PR has appropriate labels and milestones for easy identification
- [ ] PR it is assigned to the owner
- [ ] reviewers are assigned
- [ ] the PR contributes only one focused change
- [ ] It is in the appropriate column in the project board (if necessary)
- [ ] has short and clear description
- [ ] is linked to an issue (if it is related)
- [ ] feedback is addressed (if any and if it is appropriate feedback.)

### Markdown

- [ ] the markdown source is formatted
- [ ] spelling and grammar is correct in all text
- [ ] The markdown looks correct when you preview the file
- [ ] all links and images work
- [ ] any embedded code snippets are formatted

2021-12-06 12:36 UTC, arnochauveau commented on vocabulary/javascript/vartypes.md
> +
Watch out when writing things like this. `var` doesn't have limitations and `let` isn't more versatile. 

In fact, `var` and `let` do exactly the same, but are differently scoped. 
Scoping basically means: "Where are my variables available to me?"
`var` if function scoped and `let` is block scoped.

You can read more about let, const and var here: https://wesbos.com/javascript/01-the-basics/variables-and-statements/#scoping

2021-12-06 12:37 UTC, arnochauveau requested changes
See below

2021-12-06 17:16 UTC, aviv82 commented
> See comment

got it. will edit tonight!

2021-12-07 07:32 UTC, arnochauveau requested changes

2021-12-07 07:32 UTC, arnochauveau commented on vocabulary/javascript/vartypes.md
> +> unlike var it is object scoped and therefore prefered by developers today
It's block scoped, not object scoped. 😃

2021-12-07 10:00 UTC, aviv82 commented on vocabulary/javascript/vartypes.md
> +> unlike var it is object scoped and therefore prefered by developers today
lol woops. 😅 fixed now!

2021-12-07 10:12 UTC, arnochauveau approved these changes

2021-12-07 10:12 UTC, merged