progress-bar-snippet.md
lab-antwerp-1/home pull request #194
Opened 2021-12-04 14:48 UTC by omerjava

## Checklists

### General Checks

- [ ] the branch is up to date with `main`/`master`
- [ ] the code works when pulled and run locally
- [ ] All CI checks pass
- [ ] all conflicts are resolved (if any)
- [ ] PR has a descriptive title
- [ ] PR has appropriate labels and milestones for easy identification
- [ ] PR it is assigned to the owner
- [ ] reviewers are assigned
- [ ] the PR contributes only one focused change
- [ ] It is in the appropriate column in the project board (if necessary)
- [ ] has short and clear description
- [ ] is linked to an issue (if it is related)
- [ ] feedback is addressed (if any and if it is appropriate feedback.)

### Markdown

- [ ] the markdown source is formatted
- [ ] spelling and grammar is correct in all text
- [ ] The markdown looks correct when you preview the file
- [ ] all links and images work
- [ ] any embedded code snippets are formatted

2021-12-06 12:48 UTC, arnochauveau requested changes
Nice snippet, @omerjava. 
I've added some tips for formatting your MD file. 
Also try to pay attention to indenting to make your code more readable (for example the body of the if-statement) and your usage of var instead of let and const (bad practice to use var).

2021-12-06 12:48 UTC, arnochauveau commented on snippets/javascript/progress-bar-snippet.md
> +
Hey @omerjava small tip: in MD you can add syntax highlighting to code blocks: 
``` 
           ``` html
               <!-- your html here -->
            ```
            ``` js
             // your JS here
            ```
 ```
 
 which will look like this: 
 ```html
<!-- your html here -->
```
```js 
// your js here
```

or for your example: 

```html
<!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <title>Progress Bar</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" type="text/css" media="screen" href="style.css" />
        <script src="script.js"></script>
    </head>
    <body>
        <label for="file">Downloading progress:</label>
        <progress value="0" max="100" id="progressBar"></progress>
    </body>
    </html>
```

```js
var timeLeft = 100;
    var downloadTimer = setInterval(function() {
        if (timeLeft <= 0) {
        clearInterval(downloadTimer);
        }
        document.getElementById("progressBar").value = 100 - timeLeft;
        timeLeft -= 1;
    }, 100);
```

2021-12-10 00:01 UTC, omerjava commented
> Nice snippet, @omerjava. I've added some tips for formatting your MD file. Also try to pay attention to indenting to make your code more readable (for example the body of the if-statement) and your usage of var instead of let and const (bad practice to use var).

@arnochauveau Thanks for the tips. I updated it!

2021-12-10 07:38 UTC, arnochauveau commented
> > Nice snippet, @omerjava. I've added some tips for formatting your MD file. Also try to pay attention to indenting to make your code more readable (for example the body of the if-statement) and your usage of var instead of let and const (bad practice to use var).
> 
> @arnochauveau Thanks for the tips. I updated it!

Hey @omerjava the 

html here and js here snippets were as an example, you don't need to add those to use the syntax highlighting 🙂

I've removed those for you, take a look at my commit to see what I mean.

2021-12-10 07:38 UTC, arnochauveau approved these changes

2021-12-10 07:39 UTC, merged

2021-12-10 13:23 UTC, omerjava commented
> > > Nice snippet, @omerjava. I've added some tips for formatting your MD file. Also try to pay attention to indenting to make your code more readable (for example the body of the if-statement) and your usage of var instead of let and const (bad practice to use var).
> > 
> > 
> > @arnochauveau Thanks for the tips. I updated it!
> 
> Hey @omerjava the
> 
> html here and js here snippets were as an example, you don't need to add those to use the syntax highlighting 🙂
> 
> I've removed those for you, take a look at [my commit](https://github.com/lab-antwerp-1/home/pull/194/commits/c692412042fc9dd2d72d5eb9dcece559eb7cf128) to see what I mean.

Ok 🙂 Thank you!