Vocabulary - Khaled
lab-antwerp-1/home pull request #67
Opened 2021-10-12 17:36 UTC by Levaii

2021-11-17 14:04 UTC, gelilaa submitted a review, later dismissed
@Levaii can you please fix the conflict?

2021-11-29 08:39 UTC, arnochauveau commented
@Levaii Can you please revert the changes other than `vocabulary/workflow.md` ? 
These seem to be accidental changes and also the source of your merge conflicts.

You can do so by running the following commands in your terminal: 

```bash
git checkout origin main -- README.md
git checkout origin main -- student-bios/Tahmina.md
```

You can then commit the changes and push them.

2021-12-03 19:42 UTC, Levaii commented
hey @arnochauveau
I did revert the changes and did those commands, it seems to be the same issue, any tip?

2021-12-06 10:29 UTC, arnochauveau requested changes

2021-12-06 10:29 UTC, arnochauveau commented on README.md
> +>
Please revert changes to this file. You can use `git checkout origin main -- README.md`

2021-12-06 10:29 UTC, arnochauveau commented on student-bios/Tahmina.md
> +
please revert changes to this file, you can use `git checkout origin main -- student-bios/Tahmina.md`

2021-12-06 10:31 UTC, arnochauveau commented
> hey @arnochauveau I did revert the changes and did those commands, it seems to be the same issue, any tip?

Did you add,  commit and push after? 
```bash
git add .
git commit -m "revert whitespace changes"
git push
```

2021-12-11 13:40 UTC, Levaii commented
@arnochauveau Yes I added a commit and pushed it.

2021-12-14 08:20 UTC, arnochauveau commented
> @arnochauveau Yes I added a commit and pushed it.

I'm sorry, the right command was `git checkout origin/main -- README.md`, my bad. I've fixed it for you! 🙂

2021-12-14 08:21 UTC, arnochauveau approved these changes

2021-12-14 08:21 UTC, merged